### ISSUE TITLE
Cannot be used as an outlined font (using CSS text-stroke/fill)

### ISSUE THREAD

**Issue by willbroderick** [Instrument/instrument-sans#4]
Using the TTF directly on a website, or via Google Fonts, I apply the following CSS to it:
```
-webkit-text-stroke: .01em black;
-webkit-text-fill-color: white;
```
It results in this appearance:
![image](https://github.com/user-attachments/assets/ef820bfc-1445-4503-8940-155464114c12)

Where you can clearly see the 'internal' lines of the font. This happens anywhere this font is used.

I would expect a tidy outline, like many other fonts have.
Here is Lato for comparison:
![image](https://github.com/user-attachments/assets/7b08492e-c104-454f-9472-fe26afa56b5f)

**Comment by willbroderick** [comment]
Apologies, closing as this only appears on the Google Font version. It looks perfect when using the TTF file from this repo. Opening an issue there.

**Comment by meewgumi** [comment]
wait this is lit i'm getting the google fonts version now
